# Generated by Django 4.1 on 2022-10-08 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slide_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='time_to_show',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='title',
            field=models.CharField(default='Title', max_length=64),
        ),
    ]
