# Generated by Django 4.1 on 2022-10-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slide_show', '0002_slideshow_description_slideshow_time_to_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='slideshow',
            unique_together={('secret_number', 'user')},
        ),
        migrations.AddIndex(
            model_name='slideshow',
            index=models.Index(fields=['secret_number', 'user'], name='slide_show__secret__71a181_idx'),
        ),
    ]
