# Generated by Django 4.1 on 2022-10-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slide_show', '0003_alter_slideshow_user_alter_slideshow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='time_to_show',
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('time_to_show', models.IntegerField(default=10)),
                ('slide_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slide_show.slideshow')),
            ],
        ),
    ]
